<?php

namespace Member\Controller;

use Common\Controller\CommonController;
use Think\Controller;

//会员中心
class UserController extends CommonController
{

    public function _initialize ( $status = false )
    {
        
        parent::_initialize(false); // TODO: Change the autogenerated stub
    }
    
    //会员中心
    public function userInfo()
    {
        $user_info=D('VipUser')->UserInfo();
//        dump($user_info);
        $this->assign('user_info',$user_info);
        $this->display();

    }

    //实名认证
    public function realName(){
    
        $this->display('real_name');
    }


}
