<?php

namespace Member\Controller;

use Common\Controller\CommonController;
use Think\Controller;

//会员中心
class UserController extends CommonController
{

    public function _initialize ( $status = false )
    {
        
        parent::_initialize(false); // TODO: Change the autogenerated stub
    }
    
    //会员中心
    public function UserInfo()
    {


        $this->display();

    }



}
