<?php

namespace Member\Controller;

use Common\Controller\CommonController;
use Think\Controller;

//会员中心
class UserController extends CommonController
{

    public function _initialize ( $status = false )
    {
        
        $all=parent::_initialize(true); // TODO: Change the autogenerated stub
//        var_dump($all);
    }
    
    //会员中心
    public function userInfo()
    {
        $user_info=D('VipUser')->UserInfo();
        $this->assign('user_info',$user_info);
        $this->display();

    }

    //实名认证
    public function realName(){
    
        $this->display();
    }


}
